//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.25 at 10:05:13 PM EAT 
//


package com.dewcis.ptg.beans;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dewcis.ptg.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SchemaValidationFaultDetail_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "SchemaValidationFaultDetail");
    private final static QName _LoginRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "LoginRequest");
    private final static QName _LoginResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "LoginResponse");
    private final static QName _LogoutRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "LogoutRequest");
    private final static QName _LogoutResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "LogoutResponse");
    private final static QName _AccountInfoRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AccountInfoRequest");
    private final static QName _AccountInfoResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AccountInfoResponse");
    private final static QName _PinInfoRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "PinInfoRequest");
    private final static QName _PinInfoResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "PinInfoResponse");
    private final static QName _CallerInfoRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "CallerInfoRequest");
    private final static QName _CallerInfoResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "CallerInfoResponse");
    private final static QName _CustomerDataRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "CustomerDataRequest");
    private final static QName _CustomerDataResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "CustomerDataResponse");
    private final static QName _TelephonesEmailsRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "TelephonesEmailsRequest");
    private final static QName _TelephonesEmailsResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "TelephonesEmailsResponse");
    private final static QName _ReferenceInstancesRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "ReferenceInstancesRequest");
    private final static QName _ReferenceInstancesResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "ReferenceInstancesResponse");
    private final static QName _RouteSettingsRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RouteSettingsRequest");
    private final static QName _RouteSettingsResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RouteSettingsResponse");
    private final static QName _AvailableInstructionTypesRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AvailableInstructionTypesRequest");
    private final static QName _AvailableInstructionTypesResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AvailableInstructionTypesResponse");
    private final static QName _AirportsRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AirportsRequest");
    private final static QName _AirportsResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AirportsResponse");
    private final static QName _TrainStationsRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "TrainStationsRequest");
    private final static QName _TrainStationsResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "TrainStationsResponse");
    private final static QName _AddressSearchByStringRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AddressSearchByStringRequest");
    private final static QName _AddressSearchByStringResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AddressSearchByStringResponse");
    private final static QName _AddressSearchByCoordinatesRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AddressSearchByCoordinatesRequest");
    private final static QName _AddressSearchByCoordinatesResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AddressSearchByCoordinatesResponse");
    private final static QName _AdlerWsGetDetailedAddressRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AdlerWsGetDetailedAddressRequest");
    private final static QName _AdlerWsGetDetailedAddressResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AdlerWsGetDetailedAddressResponse");
    private final static QName _QuotationRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "QuotationRequest");
    private final static QName _QuotationResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "QuotationResponse");
    private final static QName _DelayRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "DelayRequest");
    private final static QName _DelayResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "DelayResponse");
    private final static QName _ValidateReferencesRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "ValidateReferencesRequest");
    private final static QName _ValidateReferencesResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "ValidateReferencesResponse");
    private final static QName _ValidateJobRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "ValidateJobRequest");
    private final static QName _ValidateJobResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "ValidateJobResponse");
    private final static QName _BookJobRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "BookJobRequest");
    private final static QName _BookJobResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "BookJobResponse");
    private final static QName _CompletePaymentRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "CompletePaymentRequest");
    private final static QName _CompletePaymentResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "CompletePaymentResponse");
    private final static QName _AmendJobRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AmendJobRequest");
    private final static QName _AmendJobResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "AmendJobResponse");
    private final static QName _CancelJobRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "CancelJobRequest");
    private final static QName _CancelJobResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "CancelJobResponse");
    private final static QName _JobStatusRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "JobStatusRequest");
    private final static QName _JobStatusResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "JobStatusResponse");
    private final static QName _JobPriceDetailsRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "JobPriceDetailsRequest");
    private final static QName _JobPriceDetailsResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "JobPriceDetailsResponse");
    private final static QName _ReceiptRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "ReceiptRequest");
    private final static QName _ReceiptResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "ReceiptResponse");
    private final static QName _ZoneInfoRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "ZoneInfoRequest");
    private final static QName _ZoneInfoResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "ZoneInfoResponse");
    private final static QName _FleetRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "FleetRequest");
    private final static QName _FleetResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "FleetResponse");
    private final static QName _JobStatusChangedRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "JobStatusChangedRequest");
    private final static QName _JobStatusChangedResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "JobStatusChangedResponse");
    private final static QName _JobReadyForInvoiceRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "JobReadyForInvoiceRequest");
    private final static QName _JobReadyForInvoiceResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "JobReadyForInvoiceResponse");
    private final static QName _RetailRegisterRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailRegisterRequest");
    private final static QName _RetailRegisterResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailRegisterResponse");
    private final static QName _RetailLoginRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailLoginRequest");
    private final static QName _RetailLoginResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailLoginResponse");
    private final static QName _RetailPasswordRecoveryRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailPasswordRecoveryRequest");
    private final static QName _RetailPasswordRecoveryResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailPasswordRecoveryResponse");
    private final static QName _RetailCheckUserExistsRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailCheckUserExistsRequest");
    private final static QName _RetailCheckUserExistsResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailCheckUserExistsResponse");
    private final static QName _RetailChangePasswordRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailChangePasswordRequest");
    private final static QName _RetailChangePasswordResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailChangePasswordResponse");
    private final static QName _RetailChangePhoneRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailChangePhoneRequest");
    private final static QName _RetailChangePhoneResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailChangePhoneResponse");
    private final static QName _RetailUpdateProfileRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailUpdateProfileRequest");
    private final static QName _RetailUpdateProfileResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailUpdateProfileResponse");
    private final static QName _RetailLoadProfileRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailLoadProfileRequest");
    private final static QName _RetailLoadProfileResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailLoadProfileResponse");
    private final static QName _RetailLogoutRequest_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailLogoutRequest");
    private final static QName _RetailLogoutResponse_QNAME = new QName("http://www.haulmont.com/sherlock/adler", "RetailLogoutResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dewcis.ptg.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SchemaValidationFaultDetail }
     * 
     */
    public SchemaValidationFaultDetail createSchemaValidationFaultDetail() {
        return new SchemaValidationFaultDetail();
    }

    /**
     * Create an instance of {@link LoginRequest }
     * 
     */
    public LoginRequest createLoginRequest() {
        return new LoginRequest();
    }

    /**
     * Create an instance of {@link LoginResponse }
     * 
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link LogoutRequest }
     * 
     */
    public LogoutRequest createLogoutRequest() {
        return new LogoutRequest();
    }

    /**
     * Create an instance of {@link LogoutResponse }
     * 
     */
    public LogoutResponse createLogoutResponse() {
        return new LogoutResponse();
    }

    /**
     * Create an instance of {@link AccountInfoRequest }
     * 
     */
    public AccountInfoRequest createAccountInfoRequest() {
        return new AccountInfoRequest();
    }

    /**
     * Create an instance of {@link AccountInfoResponse }
     * 
     */
    public AccountInfoResponse createAccountInfoResponse() {
        return new AccountInfoResponse();
    }

    /**
     * Create an instance of {@link PinRequest }
     * 
     */
    public PinRequest createPinRequest() {
        return new PinRequest();
    }

    /**
     * Create an instance of {@link PinResponse }
     * 
     */
    public PinResponse createPinResponse() {
        return new PinResponse();
    }

    /**
     * Create an instance of {@link CallerInfoRequest }
     * 
     */
    public CallerInfoRequest createCallerInfoRequest() {
        return new CallerInfoRequest();
    }

    /**
     * Create an instance of {@link CallerInfoResponse }
     * 
     */
    public CallerInfoResponse createCallerInfoResponse() {
        return new CallerInfoResponse();
    }

    /**
     * Create an instance of {@link CustomerDataRequest }
     * 
     */
    public CustomerDataRequest createCustomerDataRequest() {
        return new CustomerDataRequest();
    }

    /**
     * Create an instance of {@link CustomerDataResponse }
     * 
     */
    public CustomerDataResponse createCustomerDataResponse() {
        return new CustomerDataResponse();
    }

    /**
     * Create an instance of {@link TelephoneEmailsRequest }
     * 
     */
    public TelephoneEmailsRequest createTelephoneEmailsRequest() {
        return new TelephoneEmailsRequest();
    }

    /**
     * Create an instance of {@link TelephoneEmailsResponse }
     * 
     */
    public TelephoneEmailsResponse createTelephoneEmailsResponse() {
        return new TelephoneEmailsResponse();
    }

    /**
     * Create an instance of {@link ReferenceInstancesRequest }
     * 
     */
    public ReferenceInstancesRequest createReferenceInstancesRequest() {
        return new ReferenceInstancesRequest();
    }

    /**
     * Create an instance of {@link ReferenceInstancesResponse }
     * 
     */
    public ReferenceInstancesResponse createReferenceInstancesResponse() {
        return new ReferenceInstancesResponse();
    }

    /**
     * Create an instance of {@link RouteSettingsRequest }
     * 
     */
    public RouteSettingsRequest createRouteSettingsRequest() {
        return new RouteSettingsRequest();
    }

    /**
     * Create an instance of {@link RouteSettingsResponse }
     * 
     */
    public RouteSettingsResponse createRouteSettingsResponse() {
        return new RouteSettingsResponse();
    }

    /**
     * Create an instance of {@link InstructionTypesRequest }
     * 
     */
    public InstructionTypesRequest createInstructionTypesRequest() {
        return new InstructionTypesRequest();
    }

    /**
     * Create an instance of {@link InstructionTypesResponse }
     * 
     */
    public InstructionTypesResponse createInstructionTypesResponse() {
        return new InstructionTypesResponse();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link AirportsResponse }
     * 
     */
    public AirportsResponse createAirportsResponse() {
        return new AirportsResponse();
    }

    /**
     * Create an instance of {@link TrainStationsResponse }
     * 
     */
    public TrainStationsResponse createTrainStationsResponse() {
        return new TrainStationsResponse();
    }

    /**
     * Create an instance of {@link AddressSearchByStringRequest }
     * 
     */
    public AddressSearchByStringRequest createAddressSearchByStringRequest() {
        return new AddressSearchByStringRequest();
    }

    /**
     * Create an instance of {@link AddressSearchResponse }
     * 
     */
    public AddressSearchResponse createAddressSearchResponse() {
        return new AddressSearchResponse();
    }

    /**
     * Create an instance of {@link AddressSearchByCoordinatesRequest }
     * 
     */
    public AddressSearchByCoordinatesRequest createAddressSearchByCoordinatesRequest() {
        return new AddressSearchByCoordinatesRequest();
    }

    /**
     * Create an instance of {@link AdlerWsGetDetailedAddressRequest }
     * 
     */
    public AdlerWsGetDetailedAddressRequest createAdlerWsGetDetailedAddressRequest() {
        return new AdlerWsGetDetailedAddressRequest();
    }

    /**
     * Create an instance of {@link JobRequest }
     * 
     */
    public JobRequest createJobRequest() {
        return new JobRequest();
    }

    /**
     * Create an instance of {@link QuotationResponse }
     * 
     */
    public QuotationResponse createQuotationResponse() {
        return new QuotationResponse();
    }

    /**
     * Create an instance of {@link DelayRequest }
     * 
     */
    public DelayRequest createDelayRequest() {
        return new DelayRequest();
    }

    /**
     * Create an instance of {@link DelayResponse }
     * 
     */
    public DelayResponse createDelayResponse() {
        return new DelayResponse();
    }

    /**
     * Create an instance of {@link ValidateReferencesRequest }
     * 
     */
    public ValidateReferencesRequest createValidateReferencesRequest() {
        return new ValidateReferencesRequest();
    }

    /**
     * Create an instance of {@link ValidateReferencesResponse }
     * 
     */
    public ValidateReferencesResponse createValidateReferencesResponse() {
        return new ValidateReferencesResponse();
    }

    /**
     * Create an instance of {@link JobValidationResponse }
     * 
     */
    public JobValidationResponse createJobValidationResponse() {
        return new JobValidationResponse();
    }

    /**
     * Create an instance of {@link BookJobRequest }
     * 
     */
    public BookJobRequest createBookJobRequest() {
        return new BookJobRequest();
    }

    /**
     * Create an instance of {@link BookJobResponse }
     * 
     */
    public BookJobResponse createBookJobResponse() {
        return new BookJobResponse();
    }

    /**
     * Create an instance of {@link CompletePaymentRequest }
     * 
     */
    public CompletePaymentRequest createCompletePaymentRequest() {
        return new CompletePaymentRequest();
    }

    /**
     * Create an instance of {@link AmendJobRequest }
     * 
     */
    public AmendJobRequest createAmendJobRequest() {
        return new AmendJobRequest();
    }

    /**
     * Create an instance of {@link CancelJobRequest }
     * 
     */
    public CancelJobRequest createCancelJobRequest() {
        return new CancelJobRequest();
    }

    /**
     * Create an instance of {@link CancelJobResponse }
     * 
     */
    public CancelJobResponse createCancelJobResponse() {
        return new CancelJobResponse();
    }

    /**
     * Create an instance of {@link JobIdRequest }
     * 
     */
    public JobIdRequest createJobIdRequest() {
        return new JobIdRequest();
    }

    /**
     * Create an instance of {@link JobStatusResponse }
     * 
     */
    public JobStatusResponse createJobStatusResponse() {
        return new JobStatusResponse();
    }

    /**
     * Create an instance of {@link JobPriceDetailsRequest }
     * 
     */
    public JobPriceDetailsRequest createJobPriceDetailsRequest() {
        return new JobPriceDetailsRequest();
    }

    /**
     * Create an instance of {@link JobPriceDetailsResponse }
     * 
     */
    public JobPriceDetailsResponse createJobPriceDetailsResponse() {
        return new JobPriceDetailsResponse();
    }

    /**
     * Create an instance of {@link ReceiptRequest }
     * 
     */
    public ReceiptRequest createReceiptRequest() {
        return new ReceiptRequest();
    }

    /**
     * Create an instance of {@link ReceiptResponse }
     * 
     */
    public ReceiptResponse createReceiptResponse() {
        return new ReceiptResponse();
    }

    /**
     * Create an instance of {@link ZoneInfoRequest }
     * 
     */
    public ZoneInfoRequest createZoneInfoRequest() {
        return new ZoneInfoRequest();
    }

    /**
     * Create an instance of {@link ZoneInfoResponse }
     * 
     */
    public ZoneInfoResponse createZoneInfoResponse() {
        return new ZoneInfoResponse();
    }

    /**
     * Create an instance of {@link FleetRequest }
     * 
     */
    public FleetRequest createFleetRequest() {
        return new FleetRequest();
    }

    /**
     * Create an instance of {@link FleetResponse }
     * 
     */
    public FleetResponse createFleetResponse() {
        return new FleetResponse();
    }

    /**
     * Create an instance of {@link JobStatusChangedRequest }
     * 
     */
    public JobStatusChangedRequest createJobStatusChangedRequest() {
        return new JobStatusChangedRequest();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link JobReadyForInvoiceRequest }
     * 
     */
    public JobReadyForInvoiceRequest createJobReadyForInvoiceRequest() {
        return new JobReadyForInvoiceRequest();
    }

    /**
     * Create an instance of {@link RetailRegisterRequest }
     * 
     */
    public RetailRegisterRequest createRetailRegisterRequest() {
        return new RetailRegisterRequest();
    }

    /**
     * Create an instance of {@link RetailLoginRequest }
     * 
     */
    public RetailLoginRequest createRetailLoginRequest() {
        return new RetailLoginRequest();
    }

    /**
     * Create an instance of {@link RetailLoginResponse }
     * 
     */
    public RetailLoginResponse createRetailLoginResponse() {
        return new RetailLoginResponse();
    }

    /**
     * Create an instance of {@link RetailPasswordRecoveryRequest }
     * 
     */
    public RetailPasswordRecoveryRequest createRetailPasswordRecoveryRequest() {
        return new RetailPasswordRecoveryRequest();
    }

    /**
     * Create an instance of {@link RetailCheckUserExistsRequest }
     * 
     */
    public RetailCheckUserExistsRequest createRetailCheckUserExistsRequest() {
        return new RetailCheckUserExistsRequest();
    }

    /**
     * Create an instance of {@link RetailChangePasswordRequest }
     * 
     */
    public RetailChangePasswordRequest createRetailChangePasswordRequest() {
        return new RetailChangePasswordRequest();
    }

    /**
     * Create an instance of {@link RetailChangePhoneRequest }
     * 
     */
    public RetailChangePhoneRequest createRetailChangePhoneRequest() {
        return new RetailChangePhoneRequest();
    }

    /**
     * Create an instance of {@link RetailUpdateProfileRequest }
     * 
     */
    public RetailUpdateProfileRequest createRetailUpdateProfileRequest() {
        return new RetailUpdateProfileRequest();
    }

    /**
     * Create an instance of {@link RetailLoadProfileResponse }
     * 
     */
    public RetailLoadProfileResponse createRetailLoadProfileResponse() {
        return new RetailLoadProfileResponse();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link Account }
     * 
     */
    public Account createAccount() {
        return new Account();
    }

    /**
     * Create an instance of {@link Pin }
     * 
     */
    public Pin createPin() {
        return new Pin();
    }

    /**
     * Create an instance of {@link Individual }
     * 
     */
    public Individual createIndividual() {
        return new Individual();
    }

    /**
     * Create an instance of {@link IndividualWithStatus }
     * 
     */
    public IndividualWithStatus createIndividualWithStatus() {
        return new IndividualWithStatus();
    }

    /**
     * Create an instance of {@link CustomerBookingSettings }
     * 
     */
    public CustomerBookingSettings createCustomerBookingSettings() {
        return new CustomerBookingSettings();
    }

    /**
     * Create an instance of {@link CvcRequiredSettings }
     * 
     */
    public CvcRequiredSettings createCvcRequiredSettings() {
        return new CvcRequiredSettings();
    }

    /**
     * Create an instance of {@link AirportStopSettings }
     * 
     */
    public AirportStopSettings createAirportStopSettings() {
        return new AirportStopSettings();
    }

    /**
     * Create an instance of {@link TrainStopSettings }
     * 
     */
    public TrainStopSettings createTrainStopSettings() {
        return new TrainStopSettings();
    }

    /**
     * Create an instance of {@link CustomerProfileSettings }
     * 
     */
    public CustomerProfileSettings createCustomerProfileSettings() {
        return new CustomerProfileSettings();
    }

    /**
     * Create an instance of {@link CoordinatesAddress }
     * 
     */
    public CoordinatesAddress createCoordinatesAddress() {
        return new CoordinatesAddress();
    }

    /**
     * Create an instance of {@link DataToLoad }
     * 
     */
    public DataToLoad createDataToLoad() {
        return new DataToLoad();
    }

    /**
     * Create an instance of {@link CustomerAddress }
     * 
     */
    public CustomerAddress createCustomerAddress() {
        return new CustomerAddress();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link CreditCardInfo }
     * 
     */
    public CreditCardInfo createCreditCardInfo() {
        return new CreditCardInfo();
    }

    /**
     * Create an instance of {@link ReferenceEntity }
     * 
     */
    public ReferenceEntity createReferenceEntity() {
        return new ReferenceEntity();
    }

    /**
     * Create an instance of {@link SpecialInstructionType }
     * 
     */
    public SpecialInstructionType createSpecialInstructionType() {
        return new SpecialInstructionType();
    }

    /**
     * Create an instance of {@link SpecialInstructionParameter }
     * 
     */
    public SpecialInstructionParameter createSpecialInstructionParameter() {
        return new SpecialInstructionParameter();
    }

    /**
     * Create an instance of {@link Airport }
     * 
     */
    public Airport createAirport() {
        return new Airport();
    }

    /**
     * Create an instance of {@link Terminal }
     * 
     */
    public Terminal createTerminal() {
        return new Terminal();
    }

    /**
     * Create an instance of {@link TrainStation }
     * 
     */
    public TrainStation createTrainStation() {
        return new TrainStation();
    }

    /**
     * Create an instance of {@link TrainStationMeetingPoint }
     * 
     */
    public TrainStationMeetingPoint createTrainStationMeetingPoint() {
        return new TrainStationMeetingPoint();
    }

    /**
     * Create an instance of {@link AddressSearchRequest }
     * 
     */
    public AddressSearchRequest createAddressSearchRequest() {
        return new AddressSearchRequest();
    }

    /**
     * Create an instance of {@link PickupStatistics }
     * 
     */
    public PickupStatistics createPickupStatistics() {
        return new PickupStatistics();
    }

    /**
     * Create an instance of {@link Price }
     * 
     */
    public Price createPrice() {
        return new Price();
    }

    /**
     * Create an instance of {@link Fare }
     * 
     */
    public Fare createFare() {
        return new Fare();
    }

    /**
     * Create an instance of {@link WaitingTime }
     * 
     */
    public WaitingTime createWaitingTime() {
        return new WaitingTime();
    }

    /**
     * Create an instance of {@link PriceAdjustment }
     * 
     */
    public PriceAdjustment createPriceAdjustment() {
        return new PriceAdjustment();
    }

    /**
     * Create an instance of {@link SpecialInstruction }
     * 
     */
    public SpecialInstruction createSpecialInstruction() {
        return new SpecialInstruction();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link ReferenceValidationInfo }
     * 
     */
    public ReferenceValidationInfo createReferenceValidationInfo() {
        return new ReferenceValidationInfo();
    }

    /**
     * Create an instance of {@link BaseJob }
     * 
     */
    public BaseJob createBaseJob() {
        return new BaseJob();
    }

    /**
     * Create an instance of {@link Caller }
     * 
     */
    public Caller createCaller() {
        return new Caller();
    }

    /**
     * Create an instance of {@link CreditCard }
     * 
     */
    public CreditCard createCreditCard() {
        return new CreditCard();
    }

    /**
     * Create an instance of {@link BillingAddress }
     * 
     */
    public BillingAddress createBillingAddress() {
        return new BillingAddress();
    }

    /**
     * Create an instance of {@link RouteInfo }
     * 
     */
    public RouteInfo createRouteInfo() {
        return new RouteInfo();
    }

    /**
     * Create an instance of {@link JobInfo }
     * 
     */
    public JobInfo createJobInfo() {
        return new JobInfo();
    }

    /**
     * Create an instance of {@link BaseActor }
     * 
     */
    public BaseActor createBaseActor() {
        return new BaseActor();
    }

    /**
     * Create an instance of {@link Actor }
     * 
     */
    public Actor createActor() {
        return new Actor();
    }

    /**
     * Create an instance of {@link Stop }
     * 
     */
    public Stop createStop() {
        return new Stop();
    }

    /**
     * Create an instance of {@link AirportStopDetails }
     * 
     */
    public AirportStopDetails createAirportStopDetails() {
        return new AirportStopDetails();
    }

    /**
     * Create an instance of {@link TrainStopDetails }
     * 
     */
    public TrainStopDetails createTrainStopDetails() {
        return new TrainStopDetails();
    }

    /**
     * Create an instance of {@link Job }
     * 
     */
    public Job createJob() {
        return new Job();
    }

    /**
     * Create an instance of {@link ValidationMessage }
     * 
     */
    public ValidationMessage createValidationMessage() {
        return new ValidationMessage();
    }

    /**
     * Create an instance of {@link SecurePaymentParameters }
     * 
     */
    public SecurePaymentParameters createSecurePaymentParameters() {
        return new SecurePaymentParameters();
    }

    /**
     * Create an instance of {@link RedirectInfo }
     * 
     */
    public RedirectInfo createRedirectInfo() {
        return new RedirectInfo();
    }

    /**
     * Create an instance of {@link RedirectParameter }
     * 
     */
    public RedirectParameter createRedirectParameter() {
        return new RedirectParameter();
    }

    /**
     * Create an instance of {@link SecurePaymentParameter }
     * 
     */
    public SecurePaymentParameter createSecurePaymentParameter() {
        return new SecurePaymentParameter();
    }

    /**
     * Create an instance of {@link JobDriverInfo }
     * 
     */
    public JobDriverInfo createJobDriverInfo() {
        return new JobDriverInfo();
    }

    /**
     * Create an instance of {@link FinalJob }
     * 
     */
    public FinalJob createFinalJob() {
        return new FinalJob();
    }

    /**
     * Create an instance of {@link FinalStop }
     * 
     */
    public FinalStop createFinalStop() {
        return new FinalStop();
    }

    /**
     * Create an instance of {@link AdditionalPayment }
     * 
     */
    public AdditionalPayment createAdditionalPayment() {
        return new AdditionalPayment();
    }

    /**
     * Create an instance of {@link JobExtra }
     * 
     */
    public JobExtra createJobExtra() {
        return new JobExtra();
    }

    /**
     * Create an instance of {@link Tax }
     * 
     */
    public Tax createTax() {
        return new Tax();
    }

    /**
     * Create an instance of {@link Charge }
     * 
     */
    public Charge createCharge() {
        return new Charge();
    }

    /**
     * Create an instance of {@link DriverInfo }
     * 
     */
    public DriverInfo createDriverInfo() {
        return new DriverInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SchemaValidationFaultDetail }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SchemaValidationFaultDetail }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "SchemaValidationFaultDetail")
    public JAXBElement<SchemaValidationFaultDetail> createSchemaValidationFaultDetail(SchemaValidationFaultDetail value) {
        return new JAXBElement<SchemaValidationFaultDetail>(_SchemaValidationFaultDetail_QNAME, SchemaValidationFaultDetail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LoginRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "LoginRequest")
    public JAXBElement<LoginRequest> createLoginRequest(LoginRequest value) {
        return new JAXBElement<LoginRequest>(_LoginRequest_QNAME, LoginRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LoginResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "LoginResponse")
    public JAXBElement<LoginResponse> createLoginResponse(LoginResponse value) {
        return new JAXBElement<LoginResponse>(_LoginResponse_QNAME, LoginResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogoutRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LogoutRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "LogoutRequest")
    public JAXBElement<LogoutRequest> createLogoutRequest(LogoutRequest value) {
        return new JAXBElement<LogoutRequest>(_LogoutRequest_QNAME, LogoutRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogoutResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LogoutResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "LogoutResponse")
    public JAXBElement<LogoutResponse> createLogoutResponse(LogoutResponse value) {
        return new JAXBElement<LogoutResponse>(_LogoutResponse_QNAME, LogoutResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountInfoRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AccountInfoRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "AccountInfoRequest")
    public JAXBElement<AccountInfoRequest> createAccountInfoRequest(AccountInfoRequest value) {
        return new JAXBElement<AccountInfoRequest>(_AccountInfoRequest_QNAME, AccountInfoRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountInfoResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AccountInfoResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "AccountInfoResponse")
    public JAXBElement<AccountInfoResponse> createAccountInfoResponse(AccountInfoResponse value) {
        return new JAXBElement<AccountInfoResponse>(_AccountInfoResponse_QNAME, AccountInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PinRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PinRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "PinInfoRequest")
    public JAXBElement<PinRequest> createPinInfoRequest(PinRequest value) {
        return new JAXBElement<PinRequest>(_PinInfoRequest_QNAME, PinRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PinResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PinResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "PinInfoResponse")
    public JAXBElement<PinResponse> createPinInfoResponse(PinResponse value) {
        return new JAXBElement<PinResponse>(_PinInfoResponse_QNAME, PinResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CallerInfoRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CallerInfoRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "CallerInfoRequest")
    public JAXBElement<CallerInfoRequest> createCallerInfoRequest(CallerInfoRequest value) {
        return new JAXBElement<CallerInfoRequest>(_CallerInfoRequest_QNAME, CallerInfoRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CallerInfoResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CallerInfoResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "CallerInfoResponse")
    public JAXBElement<CallerInfoResponse> createCallerInfoResponse(CallerInfoResponse value) {
        return new JAXBElement<CallerInfoResponse>(_CallerInfoResponse_QNAME, CallerInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerDataRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CustomerDataRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "CustomerDataRequest")
    public JAXBElement<CustomerDataRequest> createCustomerDataRequest(CustomerDataRequest value) {
        return new JAXBElement<CustomerDataRequest>(_CustomerDataRequest_QNAME, CustomerDataRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerDataResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CustomerDataResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "CustomerDataResponse")
    public JAXBElement<CustomerDataResponse> createCustomerDataResponse(CustomerDataResponse value) {
        return new JAXBElement<CustomerDataResponse>(_CustomerDataResponse_QNAME, CustomerDataResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TelephoneEmailsRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TelephoneEmailsRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "TelephonesEmailsRequest")
    public JAXBElement<TelephoneEmailsRequest> createTelephonesEmailsRequest(TelephoneEmailsRequest value) {
        return new JAXBElement<TelephoneEmailsRequest>(_TelephonesEmailsRequest_QNAME, TelephoneEmailsRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TelephoneEmailsResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TelephoneEmailsResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "TelephonesEmailsResponse")
    public JAXBElement<TelephoneEmailsResponse> createTelephonesEmailsResponse(TelephoneEmailsResponse value) {
        return new JAXBElement<TelephoneEmailsResponse>(_TelephonesEmailsResponse_QNAME, TelephoneEmailsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceInstancesRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ReferenceInstancesRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "ReferenceInstancesRequest")
    public JAXBElement<ReferenceInstancesRequest> createReferenceInstancesRequest(ReferenceInstancesRequest value) {
        return new JAXBElement<ReferenceInstancesRequest>(_ReferenceInstancesRequest_QNAME, ReferenceInstancesRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceInstancesResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ReferenceInstancesResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "ReferenceInstancesResponse")
    public JAXBElement<ReferenceInstancesResponse> createReferenceInstancesResponse(ReferenceInstancesResponse value) {
        return new JAXBElement<ReferenceInstancesResponse>(_ReferenceInstancesResponse_QNAME, ReferenceInstancesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RouteSettingsRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RouteSettingsRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "RouteSettingsRequest")
    public JAXBElement<RouteSettingsRequest> createRouteSettingsRequest(RouteSettingsRequest value) {
        return new JAXBElement<RouteSettingsRequest>(_RouteSettingsRequest_QNAME, RouteSettingsRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RouteSettingsResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RouteSettingsResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "RouteSettingsResponse")
    public JAXBElement<RouteSettingsResponse> createRouteSettingsResponse(RouteSettingsResponse value) {
        return new JAXBElement<RouteSettingsResponse>(_RouteSettingsResponse_QNAME, RouteSettingsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstructionTypesRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InstructionTypesRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "AvailableInstructionTypesRequest")
    public JAXBElement<InstructionTypesRequest> createAvailableInstructionTypesRequest(InstructionTypesRequest value) {
        return new JAXBElement<InstructionTypesRequest>(_AvailableInstructionTypesRequest_QNAME, InstructionTypesRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstructionTypesResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InstructionTypesResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "AvailableInstructionTypesResponse")
    public JAXBElement<InstructionTypesResponse> createAvailableInstructionTypesResponse(InstructionTypesResponse value) {
        return new JAXBElement<InstructionTypesResponse>(_AvailableInstructionTypesResponse_QNAME, InstructionTypesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Request }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Request }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "AirportsRequest")
    public JAXBElement<Request> createAirportsRequest(Request value) {
        return new JAXBElement<Request>(_AirportsRequest_QNAME, Request.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AirportsResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AirportsResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "AirportsResponse")
    public JAXBElement<AirportsResponse> createAirportsResponse(AirportsResponse value) {
        return new JAXBElement<AirportsResponse>(_AirportsResponse_QNAME, AirportsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Request }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Request }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "TrainStationsRequest")
    public JAXBElement<Request> createTrainStationsRequest(Request value) {
        return new JAXBElement<Request>(_TrainStationsRequest_QNAME, Request.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TrainStationsResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TrainStationsResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "TrainStationsResponse")
    public JAXBElement<TrainStationsResponse> createTrainStationsResponse(TrainStationsResponse value) {
        return new JAXBElement<TrainStationsResponse>(_TrainStationsResponse_QNAME, TrainStationsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressSearchByStringRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AddressSearchByStringRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "AddressSearchByStringRequest")
    public JAXBElement<AddressSearchByStringRequest> createAddressSearchByStringRequest(AddressSearchByStringRequest value) {
        return new JAXBElement<AddressSearchByStringRequest>(_AddressSearchByStringRequest_QNAME, AddressSearchByStringRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressSearchResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AddressSearchResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "AddressSearchByStringResponse")
    public JAXBElement<AddressSearchResponse> createAddressSearchByStringResponse(AddressSearchResponse value) {
        return new JAXBElement<AddressSearchResponse>(_AddressSearchByStringResponse_QNAME, AddressSearchResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressSearchByCoordinatesRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AddressSearchByCoordinatesRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "AddressSearchByCoordinatesRequest")
    public JAXBElement<AddressSearchByCoordinatesRequest> createAddressSearchByCoordinatesRequest(AddressSearchByCoordinatesRequest value) {
        return new JAXBElement<AddressSearchByCoordinatesRequest>(_AddressSearchByCoordinatesRequest_QNAME, AddressSearchByCoordinatesRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressSearchResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AddressSearchResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "AddressSearchByCoordinatesResponse")
    public JAXBElement<AddressSearchResponse> createAddressSearchByCoordinatesResponse(AddressSearchResponse value) {
        return new JAXBElement<AddressSearchResponse>(_AddressSearchByCoordinatesResponse_QNAME, AddressSearchResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdlerWsGetDetailedAddressRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AdlerWsGetDetailedAddressRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "AdlerWsGetDetailedAddressRequest")
    public JAXBElement<AdlerWsGetDetailedAddressRequest> createAdlerWsGetDetailedAddressRequest(AdlerWsGetDetailedAddressRequest value) {
        return new JAXBElement<AdlerWsGetDetailedAddressRequest>(_AdlerWsGetDetailedAddressRequest_QNAME, AdlerWsGetDetailedAddressRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressSearchResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AddressSearchResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "AdlerWsGetDetailedAddressResponse")
    public JAXBElement<AddressSearchResponse> createAdlerWsGetDetailedAddressResponse(AddressSearchResponse value) {
        return new JAXBElement<AddressSearchResponse>(_AdlerWsGetDetailedAddressResponse_QNAME, AddressSearchResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JobRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link JobRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "QuotationRequest")
    public JAXBElement<JobRequest> createQuotationRequest(JobRequest value) {
        return new JAXBElement<JobRequest>(_QuotationRequest_QNAME, JobRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QuotationResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QuotationResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "QuotationResponse")
    public JAXBElement<QuotationResponse> createQuotationResponse(QuotationResponse value) {
        return new JAXBElement<QuotationResponse>(_QuotationResponse_QNAME, QuotationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DelayRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DelayRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "DelayRequest")
    public JAXBElement<DelayRequest> createDelayRequest(DelayRequest value) {
        return new JAXBElement<DelayRequest>(_DelayRequest_QNAME, DelayRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DelayResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DelayResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "DelayResponse")
    public JAXBElement<DelayResponse> createDelayResponse(DelayResponse value) {
        return new JAXBElement<DelayResponse>(_DelayResponse_QNAME, DelayResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateReferencesRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ValidateReferencesRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "ValidateReferencesRequest")
    public JAXBElement<ValidateReferencesRequest> createValidateReferencesRequest(ValidateReferencesRequest value) {
        return new JAXBElement<ValidateReferencesRequest>(_ValidateReferencesRequest_QNAME, ValidateReferencesRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateReferencesResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ValidateReferencesResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "ValidateReferencesResponse")
    public JAXBElement<ValidateReferencesResponse> createValidateReferencesResponse(ValidateReferencesResponse value) {
        return new JAXBElement<ValidateReferencesResponse>(_ValidateReferencesResponse_QNAME, ValidateReferencesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JobRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link JobRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "ValidateJobRequest")
    public JAXBElement<JobRequest> createValidateJobRequest(JobRequest value) {
        return new JAXBElement<JobRequest>(_ValidateJobRequest_QNAME, JobRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JobValidationResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link JobValidationResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "ValidateJobResponse")
    public JAXBElement<JobValidationResponse> createValidateJobResponse(JobValidationResponse value) {
        return new JAXBElement<JobValidationResponse>(_ValidateJobResponse_QNAME, JobValidationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BookJobRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BookJobRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "BookJobRequest")
    public JAXBElement<BookJobRequest> createBookJobRequest(BookJobRequest value) {
        return new JAXBElement<BookJobRequest>(_BookJobRequest_QNAME, BookJobRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BookJobResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BookJobResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "BookJobResponse")
    public JAXBElement<BookJobResponse> createBookJobResponse(BookJobResponse value) {
        return new JAXBElement<BookJobResponse>(_BookJobResponse_QNAME, BookJobResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompletePaymentRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CompletePaymentRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "CompletePaymentRequest")
    public JAXBElement<CompletePaymentRequest> createCompletePaymentRequest(CompletePaymentRequest value) {
        return new JAXBElement<CompletePaymentRequest>(_CompletePaymentRequest_QNAME, CompletePaymentRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BookJobResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BookJobResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "CompletePaymentResponse")
    public JAXBElement<BookJobResponse> createCompletePaymentResponse(BookJobResponse value) {
        return new JAXBElement<BookJobResponse>(_CompletePaymentResponse_QNAME, BookJobResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AmendJobRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AmendJobRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "AmendJobRequest")
    public JAXBElement<AmendJobRequest> createAmendJobRequest(AmendJobRequest value) {
        return new JAXBElement<AmendJobRequest>(_AmendJobRequest_QNAME, AmendJobRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BookJobResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BookJobResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "AmendJobResponse")
    public JAXBElement<BookJobResponse> createAmendJobResponse(BookJobResponse value) {
        return new JAXBElement<BookJobResponse>(_AmendJobResponse_QNAME, BookJobResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelJobRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CancelJobRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "CancelJobRequest")
    public JAXBElement<CancelJobRequest> createCancelJobRequest(CancelJobRequest value) {
        return new JAXBElement<CancelJobRequest>(_CancelJobRequest_QNAME, CancelJobRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelJobResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CancelJobResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "CancelJobResponse")
    public JAXBElement<CancelJobResponse> createCancelJobResponse(CancelJobResponse value) {
        return new JAXBElement<CancelJobResponse>(_CancelJobResponse_QNAME, CancelJobResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JobIdRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link JobIdRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "JobStatusRequest")
    public JAXBElement<JobIdRequest> createJobStatusRequest(JobIdRequest value) {
        return new JAXBElement<JobIdRequest>(_JobStatusRequest_QNAME, JobIdRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JobStatusResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link JobStatusResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "JobStatusResponse")
    public JAXBElement<JobStatusResponse> createJobStatusResponse(JobStatusResponse value) {
        return new JAXBElement<JobStatusResponse>(_JobStatusResponse_QNAME, JobStatusResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JobPriceDetailsRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link JobPriceDetailsRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "JobPriceDetailsRequest")
    public JAXBElement<JobPriceDetailsRequest> createJobPriceDetailsRequest(JobPriceDetailsRequest value) {
        return new JAXBElement<JobPriceDetailsRequest>(_JobPriceDetailsRequest_QNAME, JobPriceDetailsRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JobPriceDetailsResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link JobPriceDetailsResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "JobPriceDetailsResponse")
    public JAXBElement<JobPriceDetailsResponse> createJobPriceDetailsResponse(JobPriceDetailsResponse value) {
        return new JAXBElement<JobPriceDetailsResponse>(_JobPriceDetailsResponse_QNAME, JobPriceDetailsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReceiptRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ReceiptRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "ReceiptRequest")
    public JAXBElement<ReceiptRequest> createReceiptRequest(ReceiptRequest value) {
        return new JAXBElement<ReceiptRequest>(_ReceiptRequest_QNAME, ReceiptRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReceiptResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ReceiptResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "ReceiptResponse")
    public JAXBElement<ReceiptResponse> createReceiptResponse(ReceiptResponse value) {
        return new JAXBElement<ReceiptResponse>(_ReceiptResponse_QNAME, ReceiptResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZoneInfoRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ZoneInfoRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "ZoneInfoRequest")
    public JAXBElement<ZoneInfoRequest> createZoneInfoRequest(ZoneInfoRequest value) {
        return new JAXBElement<ZoneInfoRequest>(_ZoneInfoRequest_QNAME, ZoneInfoRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZoneInfoResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ZoneInfoResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "ZoneInfoResponse")
    public JAXBElement<ZoneInfoResponse> createZoneInfoResponse(ZoneInfoResponse value) {
        return new JAXBElement<ZoneInfoResponse>(_ZoneInfoResponse_QNAME, ZoneInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FleetRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FleetRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "FleetRequest")
    public JAXBElement<FleetRequest> createFleetRequest(FleetRequest value) {
        return new JAXBElement<FleetRequest>(_FleetRequest_QNAME, FleetRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FleetResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FleetResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "FleetResponse")
    public JAXBElement<FleetResponse> createFleetResponse(FleetResponse value) {
        return new JAXBElement<FleetResponse>(_FleetResponse_QNAME, FleetResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JobStatusChangedRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link JobStatusChangedRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "JobStatusChangedRequest")
    public JAXBElement<JobStatusChangedRequest> createJobStatusChangedRequest(JobStatusChangedRequest value) {
        return new JAXBElement<JobStatusChangedRequest>(_JobStatusChangedRequest_QNAME, JobStatusChangedRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Response }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Response }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "JobStatusChangedResponse")
    public JAXBElement<Response> createJobStatusChangedResponse(Response value) {
        return new JAXBElement<Response>(_JobStatusChangedResponse_QNAME, Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JobReadyForInvoiceRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link JobReadyForInvoiceRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "JobReadyForInvoiceRequest")
    public JAXBElement<JobReadyForInvoiceRequest> createJobReadyForInvoiceRequest(JobReadyForInvoiceRequest value) {
        return new JAXBElement<JobReadyForInvoiceRequest>(_JobReadyForInvoiceRequest_QNAME, JobReadyForInvoiceRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Response }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Response }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "JobReadyForInvoiceResponse")
    public JAXBElement<Response> createJobReadyForInvoiceResponse(Response value) {
        return new JAXBElement<Response>(_JobReadyForInvoiceResponse_QNAME, Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetailRegisterRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RetailRegisterRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "RetailRegisterRequest")
    public JAXBElement<RetailRegisterRequest> createRetailRegisterRequest(RetailRegisterRequest value) {
        return new JAXBElement<RetailRegisterRequest>(_RetailRegisterRequest_QNAME, RetailRegisterRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Response }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Response }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "RetailRegisterResponse")
    public JAXBElement<Response> createRetailRegisterResponse(Response value) {
        return new JAXBElement<Response>(_RetailRegisterResponse_QNAME, Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetailLoginRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RetailLoginRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "RetailLoginRequest")
    public JAXBElement<RetailLoginRequest> createRetailLoginRequest(RetailLoginRequest value) {
        return new JAXBElement<RetailLoginRequest>(_RetailLoginRequest_QNAME, RetailLoginRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetailLoginResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RetailLoginResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "RetailLoginResponse")
    public JAXBElement<RetailLoginResponse> createRetailLoginResponse(RetailLoginResponse value) {
        return new JAXBElement<RetailLoginResponse>(_RetailLoginResponse_QNAME, RetailLoginResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetailPasswordRecoveryRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RetailPasswordRecoveryRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "RetailPasswordRecoveryRequest")
    public JAXBElement<RetailPasswordRecoveryRequest> createRetailPasswordRecoveryRequest(RetailPasswordRecoveryRequest value) {
        return new JAXBElement<RetailPasswordRecoveryRequest>(_RetailPasswordRecoveryRequest_QNAME, RetailPasswordRecoveryRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Response }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Response }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "RetailPasswordRecoveryResponse")
    public JAXBElement<Response> createRetailPasswordRecoveryResponse(Response value) {
        return new JAXBElement<Response>(_RetailPasswordRecoveryResponse_QNAME, Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetailCheckUserExistsRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RetailCheckUserExistsRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "RetailCheckUserExistsRequest")
    public JAXBElement<RetailCheckUserExistsRequest> createRetailCheckUserExistsRequest(RetailCheckUserExistsRequest value) {
        return new JAXBElement<RetailCheckUserExistsRequest>(_RetailCheckUserExistsRequest_QNAME, RetailCheckUserExistsRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Response }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Response }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "RetailCheckUserExistsResponse")
    public JAXBElement<Response> createRetailCheckUserExistsResponse(Response value) {
        return new JAXBElement<Response>(_RetailCheckUserExistsResponse_QNAME, Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetailChangePasswordRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RetailChangePasswordRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "RetailChangePasswordRequest")
    public JAXBElement<RetailChangePasswordRequest> createRetailChangePasswordRequest(RetailChangePasswordRequest value) {
        return new JAXBElement<RetailChangePasswordRequest>(_RetailChangePasswordRequest_QNAME, RetailChangePasswordRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Response }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Response }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "RetailChangePasswordResponse")
    public JAXBElement<Response> createRetailChangePasswordResponse(Response value) {
        return new JAXBElement<Response>(_RetailChangePasswordResponse_QNAME, Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetailChangePhoneRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RetailChangePhoneRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "RetailChangePhoneRequest")
    public JAXBElement<RetailChangePhoneRequest> createRetailChangePhoneRequest(RetailChangePhoneRequest value) {
        return new JAXBElement<RetailChangePhoneRequest>(_RetailChangePhoneRequest_QNAME, RetailChangePhoneRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Response }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Response }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "RetailChangePhoneResponse")
    public JAXBElement<Response> createRetailChangePhoneResponse(Response value) {
        return new JAXBElement<Response>(_RetailChangePhoneResponse_QNAME, Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetailUpdateProfileRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RetailUpdateProfileRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "RetailUpdateProfileRequest")
    public JAXBElement<RetailUpdateProfileRequest> createRetailUpdateProfileRequest(RetailUpdateProfileRequest value) {
        return new JAXBElement<RetailUpdateProfileRequest>(_RetailUpdateProfileRequest_QNAME, RetailUpdateProfileRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Response }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Response }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "RetailUpdateProfileResponse")
    public JAXBElement<Response> createRetailUpdateProfileResponse(Response value) {
        return new JAXBElement<Response>(_RetailUpdateProfileResponse_QNAME, Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Request }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Request }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "RetailLoadProfileRequest")
    public JAXBElement<Request> createRetailLoadProfileRequest(Request value) {
        return new JAXBElement<Request>(_RetailLoadProfileRequest_QNAME, Request.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetailLoadProfileResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RetailLoadProfileResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "RetailLoadProfileResponse")
    public JAXBElement<RetailLoadProfileResponse> createRetailLoadProfileResponse(RetailLoadProfileResponse value) {
        return new JAXBElement<RetailLoadProfileResponse>(_RetailLoadProfileResponse_QNAME, RetailLoadProfileResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Request }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Request }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "RetailLogoutRequest")
    public JAXBElement<Request> createRetailLogoutRequest(Request value) {
        return new JAXBElement<Request>(_RetailLogoutRequest_QNAME, Request.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Response }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Response }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.haulmont.com/sherlock/adler", name = "RetailLogoutResponse")
    public JAXBElement<Response> createRetailLogoutResponse(Response value) {
        return new JAXBElement<Response>(_RetailLogoutResponse_QNAME, Response.class, null, value);
    }

}
